name: Build Development

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    name: Build Xperience Solution

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: src/global.json

      - name: Display .NET Info
        shell: pwsh
        run: dotnet --info

      - name: Restore NuGet Packages
        shell: pwsh
        run: dotnet restore src/KenticoSample.Web.sln
        
      - name: List NuGet Packages
        shell: pwsh
        run: |
          dotnet list src/KenticoSample.Web/KenticoSample.Web.csproj package --include-transitive

      - name: Build Solution
        shell: pwsh
        run: dotnet build src/KenticoSample.Web.sln --configuration Release --no-restore

      - name: Publish Web Application
        shell: pwsh
        run: |
          dotnet publish `
            src/KenticoSample.Web/KenticoSample.Web.csproj `
            --configuration Release `
            --no-build `
            --output publish

      - name: Verify Xperience CI Repository
        shell: pwsh
        run: |
          if (!(Test-Path "src/KenticoSample.Web/App_Data/CIRepository/repository.config")) {
              throw "Xperience CI Repository not found."
          }
          
      - name: Analyze Publish Output
        shell: pwsh
        run: |
          $size = (Get-ChildItem publish -Recurse | Measure-Object Length -Sum).Sum
          Write-Host "Total Publish Size: $([math]::Round($size / 1MB,2)) MB"

          Write-Host ""
          Write-Host "Top 20 largest files:"
          Get-ChildItem publish -Recurse -File |
            Sort-Object Length -Descending |
            Select-Object -First 20 FullName,
              @{Name="SizeMB";Expression={[math]::Round($_.Length / 1MB,2)}}

          Write-Host ""
          Write-Host "Top folders by size:"

          Get-ChildItem publish -Directory |
            ForEach-Object {
              $folderSize = (Get-ChildItem $_.FullName -Recurse -File |
                Measure-Object Length -Sum).Sum

              [PSCustomObject]@{
                Folder = $_.Name
                SizeMB = [math]::Round($folderSize / 1MB,2)
              }
            } |
            Sort-Object SizeMB -Descending
            
      - name: Compress Published Output
        shell: pwsh
        run: |
          Compress-Archive `
            -Path publish\* `
            -DestinationPath KenticoSample.Web.zip `
            -Force

      - name: Upload Published Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KenticoSample.Web
          path: KenticoSample.Web.zip
          retention-days: 2